"""empty message

Revision ID: 49311f589477
Revises: 579d5c9397c8
Create Date: 2023-04-05 15:42:38.183019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49311f589477'
down_revision = '579d5c9397c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sf_user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sf_user_table')
    # ### end Alembic commands ###
