"""empty message

Revision ID: 4f9d8806e832
Revises: 8cd196a7950f
Create Date: 2023-04-11 15:56:01.376533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9d8806e832'
down_revision = '8cd196a7950f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sf_user_table')
    op.drop_table('sample')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sample_pkey'),
    sa.UniqueConstraint('email', name='sample_email_key')
    )
    op.create_table('sf_user_table',
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('id_changed', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
