"""empty message

Revision ID: 5e8c5de3f4da
Revises: 49311f589477
Create Date: 2023-04-05 15:43:35.636997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8c5de3f4da'
down_revision = '49311f589477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_user_table', sa.Column('id_changed', sa.Integer(), nullable=False))
    op.drop_column('sf_user_table', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_user_table', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('sf_user_table', 'id_changed')
    # ### end Alembic commands ###
