"""empty message

Revision ID: baf185623908
Revises: 5e8c5de3f4da
Create Date: 2023-04-05 15:50:03.572245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf185623908'
down_revision = '5e8c5de3f4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sf_user_table_email_key', 'sf_user_table', type_='unique')
    op.drop_column('sf_user_table', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sf_user_table', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint('sf_user_table_email_key', 'sf_user_table', ['email'])
    # ### end Alembic commands ###
