"""empty message

Revision ID: e90510883eb2
Revises: 4f9d8806e832
Create Date: 2023-04-11 16:01:29.383620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90510883eb2'
down_revision = '4f9d8806e832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameA', sa.String(length=80), nullable=True),
    sa.Column('B', sa.String(length=80), nullable=True),
    sa.Column('C', sa.String(length=80), nullable=True),
    sa.Column('D', sa.String(length=80), nullable=True),
    sa.Column('E', sa.String(length=80), nullable=True),
    sa.Column('F', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('A', sa.String(length=80), nullable=True),
    sa.Column('B', sa.String(length=80), nullable=True),
    sa.Column('C', sa.String(length=80), nullable=True),
    sa.Column('D', sa.String(length=80), nullable=True),
    sa.Column('E', sa.String(length=80), nullable=True),
    sa.Column('F', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('A', sa.String(length=80), nullable=True),
    sa.Column('B', sa.String(length=80), nullable=True),
    sa.Column('C', sa.String(length=80), nullable=True),
    sa.Column('D', sa.String(length=80), nullable=True),
    sa.Column('E', sa.String(length=80), nullable=True),
    sa.Column('F', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('A', sa.String(length=80), nullable=True),
    sa.Column('B', sa.String(length=80), nullable=True),
    sa.Column('C', sa.String(length=80), nullable=True),
    sa.Column('D', sa.String(length=80), nullable=True),
    sa.Column('E', sa.String(length=80), nullable=True),
    sa.Column('F', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_d')
    op.drop_table('table_c')
    op.drop_table('table_b')
    op.drop_table('table_a')
    # ### end Alembic commands ###
